name: Conventional Commits Check
on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Checking Conventional Commits
        run: node ./scripts/check-conventional-commits/command.mjs
        env:
          REF: ${{ github.ref }}
      
      # add document
      - name: Preview Deployment
        id: deploy
        run: yarn run deploy | tee deploy.log
        env:
          REF: ${{ github.ref }}
          GH_TOKEN: ${{ github.token }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_WIDGET_CONFIG: ${{ secrets.VERCEL_PROJECT_WIDGET_CONFIG }}  # widget playground
          VERCEL_PROJECT_WIDGET_APP: ${{ secrets.VERCEL_PROJECT_WIDGET_APP }}  # widget app
          ENABLE_PREVIEW_DEPLOY: true

    outputs:
      app_url: ${{ steps.deploy.outputs.app_url }}
      playground_url: ${{ steps.deploy.outputs.playground_url }}

  app-preview:
    runs-on: ubuntu-latest
    needs: check
    environment:
      name: app-preview
      url: ${{ steps.seturl.outputs.url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract Preview URLs
        id: seturl
        run: |
          echo "url=${{ needs.check.outputs.app_url }}">> $GITHUB_OUTPUT
          echo "${{ needs.check.outputs.app_url }}"

  playground-preview:
    runs-on: ubuntu-latest
    needs: check
    environment:
      name: playground-preview
      url: ${{ steps.seturl.outputs.url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract Preview URLs
        id: seturl
        run: |
          echo "url=${{ needs.check.outputs.playground_url }}">> $GITHUB_OUTPUT
          echo "${{ needs.check.outputs.playground_url}}"
