name: Conventional Commits Check
on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

jobs:
  check:
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ steps.extract.outputs.url1 }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract Preview URLs
        id: extract
        run: |
          echo "::set-output name=url1::https://example1.com" 
          echo "::set-output name=url2::https://example2.com"
    outputs:
      url1: ${{ steps.extract.outputs.url1 }}
      url2: ${{ steps.extract.outputs.url2 }}

  nikaru:
    runs-on: ubuntu-latest
    needs: check
    environment:
      name: nikaru
      url: https://google.com
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract Preview URLs
        run: |
          echo "Staging URL: ${{ needs.check.outputs.url1 }}, Production URL: ${{ needs.check.outputs.url2 }}"
