name: Conventional Commits Check
on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Checking Conventional Commits
        run: node ./scripts/check-conventional-commits/command.mjs
        env:
          REF: ${{ github.ref }}

      - name: Preview Deployment
        id: preview
        run: |
          output=$(yarn run deploy)
          app_url=$(echo "$output" | grep '@nikaru-dev/widget-app-url-preview' | awk -F ': ' '{print $2}')
          playground_url=$(echo "$output" | grep '@nikaru-dev/widget-playground-url-preview' | awk -F ': ' '{print $2}')
          echo "app_url=$app_url" >> $GITHUB_ENV
          echo "playground_url=$playground_url" >> $GITHUB_ENV
        env:
          REF: ${{ github.ref }}
          GH_TOKEN: ${{ github.token }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_WIDGET_CONFIG: ${{ secrets.VERCEL_PROJECT_WIDGET_CONFIG }}
          VERCEL_PROJECT_WIDGET_APP: ${{ secrets.VERCEL_PROJECT_WIDGET_APP }}
          # VERCEL_PROJECT_WALLETS: ${{ secrets.VERCEL_PROJECT_WALLETS }}
          # VERCEL_PROJECT_Q: ${{ secrets.VERCEL_PROJECT_Q }}
          # VERCEL_PROJECT_WALLET_ADAPTER: ${{ secrets.VERCEL_PROJECT_WALLET_ADAPTER }}

      - name: Add Preview URLs to PR
        uses: actions/github-script@v5
        with:
          github-token: ${{ github.token }}
          script: |
            const { data: { html_url: prUrl } } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            const app_url = process.env.app_url;
            const playground_url = process.env.playground_url;
            const commentBody = `App Preview URL: ${app_url}\nPlayground Preview URL: ${playground_url}`;
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: commentBody
            });
