name: Sync translations using Crowdin
env:
  LOCALIZATION_BRANCH_NAME: 'l10n_crowdin_translations'
  CREATE_PULL_REQUEST: true

on:
  workflow_dispatch:

  workflow_call:
    secrets:
      CROWDIN_PROJECT_ID:
        description: 'You need a crowdin project id to be set.'
        required: true
      CROWDIN_PERSONAL_TOKEN:
        description: 'You need a crowdin token to be set.'
        required: true
      PAT:
        description: 'Add a PAT to secrets.'
        required: true
    inputs:
      localization_branch_name:
        description: 'Target branch name for new commit'
        required: false
        type: string
      create_pull_request:
        description: 'It requires pull request'
        type: boolean
        required: false

jobs:
  crowdin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Env Access inputs from workflow_dispatch
        run: |
          echo "Localization Branch Name: ${{ env.LOCALIZATION_BRANCH_NAME }}"
          echo "Create Pull Request: ${{ env.CREATE_PULL_REQUEST }}"

      - name: Input Access inputs from workflow_dispatch
        run: |
          echo "Localization Branch Name: ${{ inputs.localization_branch_name }}"
          echo "Create Pull Request: ${{ inputs.create_pull_request }}"

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Extract new source
        run: yarn run i18n:extract

      - name: Crowdin push & pull translations
        uses: crowdin/github-action@v1
        id: crowdin-download
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          source: translations/en.po
          translation: translations/%two_letters_code%.po
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          commit_message: 'chore(translation): update translations [skip ci]'

          localization_branch_name: ${{inputs.localization_branch_name || env.LOCALIZATION_BRANCH_NAME}}
          create_pull_request: ${{inputs.create_pull_request || env.CREATE_PULL_REQUEST}}
          pull_request_title: '🤖chore(translation): update translations'
          pull_request_body: 'New Crowdin pull request with translations'
          pull_request_base_branch_name: 'next'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Enable auto-merge for the PR
        if: steps.crowdin-download.outputs.pull_request_url
        run: gh pr --repo $GITHUB_REPOSITORY merge ${{ steps.crowdin-download.outputs.pull_request_url }} --admin --rebase
        env:
          GITHUB_TOKEN: ${{secrets.PAT}}
