name: Publish
on:
  push:
    branches:
      - 'main'
      - 'next'

jobs:
  localization:
    if: ${{ github.ref == 'refs/heads/next' }}
    uses: ./.github/workflows/crowdin.yml

  publish:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - localization
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - run: git pull

      - name: Prepare
        uses: ./.github/actions/prepare
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build, Version & Publish packages
        run: yarn run publish
        env:
          REF: ${{ github.ref }}
          GH_TOKEN: ${{ github.token }}
