name: Publish
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - 'next'

jobs:
  publish:
    if: ${{ always() && (github.ref == 'refs/heads/main' || (github.ref == 'refs/heads/next' && github.event.pull_request.merged == true)) }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - run: git pull

      - name: Prepare
        uses: ./.github/actions/prepare
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build, Version & Publish packages
        run: yarn run publish
        env:
          REF: ${{ github.ref }}
          BASE_REF: ${{ github.event.pull_request.base.ref }}
          GH_TOKEN: ${{ github.token }}

      - name: Creating PR on next
        if: ${{ github.ref == 'refs/heads/main' }}
        run: yarn run post-release-prod
        env:
          REF: ${{ github.ref }}
          BASE_REF: ${{ github.event.pull_request.base.ref }}
          GH_TOKEN: ${{ github.token }}
