name: Publish
on:
  push:
    branches:
      - 'main'
      - 'next'
  pull_request:
    types: closed
    branches:
      - 'next'

jobs:
  localization:
    if: ${{ github.ref == 'refs/heads/next' }}
    uses: ./.github/workflows/crowdin.yml
    secrets:
      CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
      CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
      PAT: ${{ secrets.PAT }}

  publish:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - localization
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - run: git pull

      - name: Print event_name
        run: 'echo "event_name: ${{ toJson(github.event_name) }}"'

      - name: Print github.event.action
        run: 'echo "github.event.action: ${{ github.event.action }}"'

      - name: Print github.event.pull_request
        run: 'echo "github.event.pull_request: ${{ toJson(github.event.pull_request) }}"'

      - name: Prepare
        uses: ./.github/actions/prepare
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build, Version & Publish packages
        run: yarn run publish
        env:
          REF: ${{ github.ref }}
          GH_TOKEN: ${{ github.token }}

      - name: Creating PR on next
        if: ${{ github.ref == 'refs/heads/main' }}
        run: yarn run post-release-prod
        env:
          REF: ${{ github.ref }}
          GH_TOKEN: ${{ github.token }}
